version: "3"

services:
  garment_app:
    build: .
    container_name: garment_app
    command: uvicorn main:app --host 0.0.0.0 --port 1102 --reload
    ports:
      - "1102:1102"
    volumes: 
      - ./:/app
    networks:
      - my_net
    restart: always

networks:
  my_net:
      

